### ISSUE TITLE
Improvement of Clocks / Counts

### ISSUE THREAD

**Issue by andtie** [appdecentral/replicatingtypes#1]
Hey @drewmccormack. First, I want to thank you for this awesome library and the corresponding article series. 

One thing where I think an improvement might be possible is with the usage of "Lamport Counts" as outlined here: https://appdecentral.com/2020/08/20/time-for-tombstones/

Informally, it would be great if we had the following property: 
"As long as the system clock behaves `reasonable` (i.e., it does not deviate too much from the real-time), the most recent change wins."

One simple way that could be implemented is to use `TimeIntervals` instead of Integer-Counts. E.g.:
```
 internal struct LamportTimestamp: Codable, Identifiable, Comparable, Hashable {
-    var count: UInt64 = 0
+    var count: Double = 0
     var id: UUID = UUID()
     
     public mutating func tick() {
-        count += 1
+        let timeInterval = Date().timeIntervalSinceReferenceDate
+        count = timeInterval > count ? timeInterval : count + 1
         id = UUID()
     }
```

The only disadvantage I see with this solution is, that for very high Double-values, due to the loss of precision, an increment by 1.0 might eventually not be bigger. A similar issue arises with UInt64 if it overflows, albeit much later.
If this is a concern, another possible solution is to cast the TimeInterval to an UInt64 and give up on our desired property for changes that happen during the same second.

I'm curious what you think about this?

PS: Other, more complicated possible solutions are outlined in this paper: https://cse.buffalo.edu/tech-reports/2014-04.pdf

**Comment by drewmccormack** [comment]
Thanks for the feedback!

I have used timestamps as you suggest in some of my production code. In general, it is not a problem. The argument is more a theoretical one. In most practical situations, you are unlikely to have any issue using the wall clock.

What a Lamport count has going for it is that it is guaranteed to increase over time (...other than the overflow case you mention). It is very stable in this way. 

I see in your solution that you have got around the problem of an errant clock by falling back on an increment by 1. This is a pragmatic solution, though you could imagine a problem if a clock was running behind by a few seconds. Presumably, you could be constantly incrementing by 1, and never passing the test. 

In any case, I don't see any major problem with what you have done. There may be drawbacks in some very specific situations. For example, if I find two values with the same Lamport count, I know the two are concurrent. They have been changed in parallel. Using a double, I am unlikely to get the same count, so I can't say whether the two events happened in parallel.

~~This problem can get worse in a vector clock, which is really just a dictionary of lamport counts, one for each peer/device. By comparing vectors, you can determine if two events occurred in parallel, and perhaps need to be merged. With a double timestamp, you could do this too, except in the case where you pick an arbitrary time (ie count + 1). At that point, you no longer can say anything about whether two vectors represent parallel events or not.~~ Update: This is actually not true. As long as your timestamps always increase, you can compare vectors.

**Comment by andtie** [comment]
Thanks a lot for your reply.

My thinking was as follows: Instead of always adding 1 to the current count, we add some variable positive number (the seconds that passed since the last tick). This way we do not loose safety (ignoring overflow / loss of precision), but we gain real-time ordering, as long as the local clocks do not diverge too much.

> [...] For example, if I find two values with the same Lamport count, I know the two are concurrent. They have been changed in parallel. [...]

I can see that the information whether two changes are concurrent might be useful. But isn't this only the case if the number of concurrent changes is the same for both parties? For example, if party A makes 3 changes and party B makes only 2 changes, then the Lamport count differs and we can't be sure whether they are in parallel.

Perhaps it dependes on the use case? For real-time collaboration, I could see the pure Lamport working better, because you can often identify concurrent operations. For applications where long connectivity interruptions are typical, a Date-based approach where the most recent change is more likely to win might have some advantages.

Do you see any issues if the LamportTimestamp-struct would be used in the implementation of ReplicatingRegister and ReplicatingArray?

Would you be interested in a pull request where the Timestamps are unified and a user may optionally provide their own implementation? Or do you want to leave this repository largely as is such that it does not deviate too much from your article series?

**Comment by drewmccormack** [comment]
> Do you see any issues if the LamportTimestamp-struct would be used in the implementation of ReplicatingRegister and ReplicatingArray?

I don't see any real problem, no. Both approaches have advantages and disadvantages.

> Would you be interested in a pull request where the Timestamps are unified and a user may optionally provide their own implementation? Or do you want to leave this repository largely as is such that it does not deviate too much from your article series?

Indeed, I think it is better to leave this repo, because it is essentially a teaching tool which goes with the articles. But branching it, or creating your own CRDT library would be a good idea.

If there is interest in that, I could also create a new library, perhaps prepopulated with the article types, which could then be improved on and shared.

**Comment by andtie** [comment]
Okay, got it. I will play around with a fork and let you know if I think I have found a meaningful improvement.
